const Produc = [
    {
        NombreProduc: "Acetaminofen",
        Categoria: "Medicamentos",
        imagen: "../img/acetaminofen.jpeg",
        Codigo: "Acc00001",
        precio: 1500,
        Laboratorio: "MK",
        Cantidad: "8 tabletas",
        Concentrado: "352 mg",
},
{
    NombreProduc: "Dolex niños",
        Categoria: "Medicamento",
        imagen: "../img/dolex_niños.jpeg",
        Codigo: "Acc00002",
        precio: 14500,
        Laboratorio: "Glaxos",
        Cantidad: "1 frasco",
        Concentrado: "90 ml",
},
{
    NombreProduc: "Sevedol Extra Fuerte",
        Categoria: "Medicamentos",
        imagen: "../img/sevedol.jpeg",
        Codigo: "Acc00003",
        precio: 11400,
        Laboratorio: "LaFrancol",
        Cantidad: "8 tabletas",
        Concentrado: "400 mg",
},
{
    NombreProduc: "Vitamina C",
        Categoria: "Medicamento",
        imagen: "../img/vitamina_c.jpeg",
        Codigo: "Acc00004",
        precio: 5300,
        Laboratorio: "MK",
        Cantidad: "20 tabletas",
        Concentrado: "500 mg",
},
{
    NombreProduc: "Dolex Rapida Accion",
        Categoria: "Medicamento",
        imagen: "../img/dolex_rapida_accion.jpeg",
        Codigo: "Acc00005",
        precio: 21000,
        Laboratorio: "Glaxos",
        Cantidad: "24 tabletas",
        Concentrado: "500 mg",
},
    {
    NombreProduc: "Dolex Forte",
        Categoria: "Medicamento",
        imagen: "../img/dolex_forte.jpg",
        Codigo: "Acc00006",
        precio: 20000,
        Laboratorio: "Glaxos",
        Cantidad: "14 tabletas",
        Concentrado: "500 mg",
},
{
    NombreProduc: "Dolex Gripa",
        Categoria: "Medicamento",
        imagen: "../img/dolex_gripa.jpeg",
        Codigo: "Acc00007",
        precio: 15000,
        Laboratorio: "Glaxos",
        Cantidad: "12 tabletas",
        Concentrado: "400 mg",
},
{
    NombreProduc: "Pax Noche",
        Categoria: "Medicamento",
        imagen: "../img/pax_noche.jpeg",
        Codigo: "Acc00008",
        precio: 11000,
        Laboratorio: "Sanofi Aventis",
        Cantidad: "6 sobres",
        Concentrado: "500 mg",
},
{
    NombreProduc: "Pax Dia",
        Categoria: "Medicamento",
        imagen: "../img/pax_dia.png",
        Codigo: "Acc00009",
        precio: 11000,
        Laboratorio: "Glaxos",
        Cantidad: "6 tabletas",
        Concentrado: "500 mg",
},
{
    NombreProduc: "Gelicart Advance",
        Categoria: "Medicamento",
        imagen: "../img/gelicart_advance.jpeg",
        Codigo: "Acc00010",
        precio: 113000,
        Laboratorio: "Glaxos",
        Cantidad: "30 sobres",
        Concentrado: "600 Gr",
},
{
    NombreProduc: "Ensure Advance Vainilla",
        Categoria: "Nutricion",
        imagen: "../img/ensure_vainilla.jpeg",
        Codigo: "Acc00011",
        precio: 70000,
        Laboratorio: "Ensure",
        Cantidad: "1 lata",
        Concentrado: "400 gr",
},
{
    NombreProduc: "Pediasure Chocolate",
        Categoria: "Nutricion",
        imagen: "../img/pediasure_chocolate.jpeg",
        Codigo: "Acc00012",
        precio: 10000,
        Laboratorio: "Pediasure",
        Cantidad: "1 tarro",
        Concentrado: "220 ml",
},
{
    NombreProduc: "Prowhey Proteina Plus",
        Categoria: "Nutricion",
        imagen: "../img/prowhey_plus.jpeg",
        Codigo: "Acc00013",
        precio: 115000,
        Laboratorio: "Prowhey",
        Cantidad: "1 lata",
        Concentrado: "320 gr",
},
{
    NombreProduc: "Prowhey Proteina",
        Categoria: "Medicamento",
        imagen: "../img/prowhey_proteina.jpeg",
        Codigo: "Acc00014",
        precio: 11000,
        Laboratorio: "Prowhey",
        Cantidad: "1 lata",
        Concentrado: "320 gr",
},
{
    NombreProduc: "Nutren Senior",
        Categoria: "Nutricion",
        imagen: "../img/nutren_senior.jpeg",
        Codigo: "Acc00015",
        precio: 108000,
        Laboratorio: "Nutren",
        Cantidad: "1 lata",
        Concentrado: "740 gr",
},
{
    NombreProduc: "Ensure Advance Chocolate",
        Categoria: "Nutricion",
        imagen: "../img/ensure_chocolate.jpeg",
        Codigo: "Acc00016",
        precio: 9000,
        Laboratorio: "Ensure",
        Cantidad: "1 tarro",
        Concentrado: "220 ml",
},
{
    NombreProduc: "Ensure Advance Fresa",
        Categoria: "Nutricion",
        imagen: "../img/ensure_fresa.jpeg",
        Codigo: "Acc00017",
        precio: 9000,
        Laboratorio: "Ensure",
        Cantidad: "1 tarro",
        Concentrado: "220 ml",
},
{
    NombreProduc: "Hydro Fluid Eucerin",
        Categoria: "Protector Solar",
        imagen: "../img/hydro_fluid.jpeg",
        Codigo: "Acc00018",
        precio: 120000,
        Laboratorio: "Eucerin",
        Cantidad: "1 frasco",
        Concentrado: "50 ml",
},
{
    NombreProduc: "Fluido SPF",
        Categoria: "Protector Solar",
        imagen: "../img/fluido_spf.jpeg",
        Codigo: "Acc00019",
        precio: 81000,
        Laboratorio: "Avene",
        Cantidad: "1 tubo",
        Concentrado: "50 ml",
},
{
    NombreProduc: "Nude Touch Photoderm",
        Categoria: "Protector Solar",
        imagen: "../img/photoderm.jpeg",
        Codigo: "Acc00020",
        precio: 81000,
        Laboratorio: "Bioderma",
        Cantidad: "1 frasco",
        Concentrado: "40 ml",
},
{
    NombreProduc: "Intense Protect",
        Categoria: "Protector Solar",
        imagen: "../img/intense_protect.jpeg",
        Codigo: "Acc00021",
        precio: 123000,
        Laboratorio: "Avene",
        Cantidad: "1 tubo",
        Concentrado: "50 ml",
},
{
    NombreProduc: "Mineral 89",
        Categoria: "Cuidado Facial",
        imagen: "../img/mineral_89.jpeg",
        Codigo: "Acc00022",
        precio: 192000,
        Laboratorio: "Vichy",
        Cantidad: "1 frasco",
        Concentrado: "50 ml",
},
{
    NombreProduc: "Cetaphil-AC",
        Categoria: "Cuidado Facial",
        imagen: "../img/cetaphil_AC.jpeg",
        Codigo: "Acc00023",
        precio: 132000,
        Laboratorio: "Cetaphil",
        Cantidad: "1 frasco",
        Concentrado: "118 ml",
},
{
    NombreProduc: "Hydrance Optimale Serum",
        Categoria: "Cuidado Facial",
        imagen: "../img/hydrance.jpeg",
        Codigo: "Acc00024",
        precio: 137000,
        Laboratorio: "Avene",
        Cantidad: "1 frasco",
        Concentrado: "30 ml",
},
{
    NombreProduc: "Agua Termal",
        Categoria: "Cuidado Facial",
        imagen: "../img/agua_termal.jpeg",
        Codigo: "Acc00025",
        precio: 73000,
        Laboratorio: "Avene",
        Cantidad: "1 frasco",
        Concentrado: "300 ml",
},
{
    NombreProduc: "Shampoo Intensivo Anticaspa Kerium",
        Categoria: "Cabello",
        imagen: "../img/shampoo_kerium.jpeg",
        Codigo: "Acc00026",
        precio: 131000,
        Laboratorio: "La Roche Posay",
        Cantidad: "1 tarro",
        Concentrado: "125 ml",
},
{
    NombreProduc: "Shampoo Anti Caspa",
        Categoria: "Cabello",
        imagen: "../img/shampoo_dercos.jpeg",
        Codigo: "Acc00027",
        precio: 97000,
        Laboratorio: "Dercos",
        Cantidad: "1 tarro",
        Concentrado: "200 ml",
},
{
    NombreProduc: "Shampoo Estimulante Dercos",
        Categoria: "Cabello",
        imagen: "../img/shampoo_estimulante.jpeg",
        Codigo: "Acc00028",
        precio: 97000,
        Laboratorio: "Vichy",
        Cantidad: "1 tarro",
        Concentrado: "200 ml",
},
{
    NombreProduc: "Condones Today",
        Categoria: "Salud Sexual",
        imagen: "../img/today.jpeg",
        Codigo: "Acc00029",
        precio: 17000,
        Laboratorio: "Pfizer",
        Cantidad: "3 unidades",
        Concentrado: "",
},
{
    NombreProduc: "Condones Duo Lubricado",
        Categoria: "Salud Sexual",
        imagen: "../img/duo.jpeg",
        Codigo: "Acc00030",
        precio: 16500,
        Laboratorio: "Duo",
        Cantidad: "6 unidades",
        Concentrado: "",
},
{
    NombreProduc: "Gel Lubricante intimo K-Y",
        Categoria: "Salud Sexual",
        imagen: "../img/gel_lubricante.jpeg",
        Codigo: "Acc00031",
        precio: 40928,
        Laboratorio: "RB Health",
        Cantidad: "1 tubo",
        Concentrado: "100 gr",
},
{
    NombreProduc: "Pañitos Humedos Pequeñin",
        Categoria: "Maternidad",
        imagen: "../img/pañitos.jpeg",
        Codigo: "Acc00032",
        precio: 12000,
        Laboratorio: "Pequeñin",
        Cantidad: "100 unidades",
        Concentrado: "",
},
{
    NombreProduc: "Copitos de Algodon",
        Categoria: "Maternidad",
        imagen: "../img/copitos.jpeg",
        Codigo: "Acc00033",
        precio: 9800,
        Laboratorio: "Suavex",
        Cantidad: "150 unidades",
        Concentrado: "",
},
{
    NombreProduc: "Pañal Ultratrim etapa 4",
        Categoria: "Maternidad",
        imagen: "../img/pañal_winny.jpeg",
        Codigo: "Acc00034",
        precio: 62300,
        Laboratorio: "Winny",
        Cantidad: "50 unidades",
        Concentrado: "",
},
{
    NombreProduc: "Pañal Huggies Xtra-Care",
        Categoria: "Maternidad",
        imagen: "../img/pañal_huggies.jpeg",
        Codigo: "Acc00035",
        precio: 84000,
        Laboratorio: "Huggies",
        Cantidad: "50 unidades",
        Concentrado: "",
},
{
    NombreProduc: "Apronax Liquid Gels",
        Categoria: "Medicamentos",
        imagen: "../img/apronax.jpeg",
        Codigo: "Acc00036",
        precio: 16800,
        Laboratorio: "Bayer",
        Cantidad: "8 capsulas",
        Concentrado: "275 mg",
},
{
    NombreProduc: "Cafiaspirina Forte",
        Categoria: "Medicamentos",
        imagen: "../img/cafiaspirina",
        Codigo: "Acc00037",
        precio: 19000,
        Laboratorio: "Cafiaspirina",
        Cantidad: "12 tabletas",
        Concentrado: "650 mg",
},
{
    NombreProduc: "Acetaminofen Forte",
        Categoria: "Medicamentos",
        imagen: "../img/acetaminofen_forte.jpeg",
        Codigo: "Acc00038",
        precio: 50800,
        Laboratorio: "MK",
        Cantidad: "48 tabletas",
        Concentrado: "565 mg",
},
{
    NombreProduc: "Loratadina Jarabe",
        Categoria: "Medicamentos",
        imagen: "../img/loratadina.jpeg",
        Codigo: "Acc00039",
        precio: 13000,
        Laboratorio: "Genfar",
        Cantidad: "1 frasco",
        Concentrado: "100 ml",
},
{
    NombreProduc: "Betametasona MK",
        Categoria: "Medicamentos",
        imagen: "../img/betamerasona.jpeg",
        Codigo: "Acc00040",
        precio: 21500,
        Laboratorio: "Tecnoquimicas SA",
        Cantidad: "1 ampolla",
        Concentrado: "7 mg",
},
{
    NombreProduc: "Prednisolona MK",
        Categoria: "Medicamentos",
        imagen: "../img/prednisolona.jpg",
        Codigo: "Acc00041",
        precio: 67450,
        Laboratorio: "Tecnoquimicas SA",
        Cantidad: "1 frasco",
        Concentrado: "120 ml",
},
{
    NombreProduc: "Gasa Esteril Nexcare",
        Categoria: "Medicamentos",
        imagen: "../img/gasa.jpeg",
        Codigo: "Acc00042",
        precio: 14500,
        Laboratorio: "3M",
        Cantidad: "12 sobres",
        Concentrado: "",
},
{
    NombreProduc: "Repelente Stay Off",
        Categoria: "Medicamentos",
        imagen: "../img/repelente.jpg",
        Codigo: "Acc00043",
        precio: 14400,
        Laboratorio: "Stay Off",
        Cantidad: "1 frasco",
        Concentrado: "40 gr",
},
{
    NombreProduc: "Noxpirin Plus Adultos",
        Categoria: "Medicamentos",
        imagen: "../img/noxpirin.jpeg",
        Codigo: "Acc00044",
        precio: 6500,
        Laboratorio: "Siegfried",
        Cantidad: "6 capsulas",
        Concentrado: "500 mg",
},
{
    NombreProduc: "Vick VapoRub",
        Categoria: "Medicamentos",
        imagen: "../img/vick.jpeg",
        Codigo: "Acc00045",
        precio: 28000,
        Laboratorio: "Vick",
        Cantidad: "1 pote",
        Concentrado: "100 gr",
},
{
    NombreProduc: "Bellaface Suave",
        Categoria: "Medicamentos",
        imagen: "../img/bellaface.jpeg",
        Codigo: "Acc00046",
        precio: 13275,
        Laboratorio: "Bellaface",
        Cantidad: "28 tabletas",
        Concentrado: "2 mg",
},
{
    NombreProduc: "Suero Electrolif Sabor Uva",
        Categoria: "Medicamentos",
        imagen: "../img/suero_uva.jpeg",
        Codigo: "Acc00047",
        precio: 8400,
        Laboratorio: "Pisa Farmaceutica",
        Cantidad: "1 frasco",
        Concentrado: "625 ml",
},
{
    NombreProduc: "Suero Electrolif Sabor Fresa",
        Categoria: "Medicamentos",
        imagen: "../img/suero_fresa.jpeg",
        Codigo: "Acc00048",
        precio: 8400,
        Laboratorio: "Pisa Farmaceutica",
        Cantidad: "1 frasco",
        Concentrado: "625 ml",
},
{
    NombreProduc: "Vaselina Pura",
        Categoria: "Medicamentos",
        imagen: "../img/vaselina.jpeg",
        Codigo: "Acc00049",
        precio: 21000,
        Laboratorio: "Johnson & johnson",
        Cantidad: "1 pote",
        Concentrado: "100 gr",
},
{
    NombreProduc: "Complejo B",
        Categoria: "Medicamentos",
        imagen: "../img/complejo_b.jpeg",
        Codigo: "Acc00050",
        precio: 19980,
        Laboratorio: "Pharmaris",
        Cantidad: "30 capsulas",
        Concentrado: "",
}
]

